title: Liam Day
name: Liam Day
description: >-
  Technical product specialist and ex-British Army officer blending operational leadership with mobile app development expertise.
url: https://www.liamday.co.uk
baseurl: "/liamday-site"

permalink: pretty
timezone: Europe/London

collections:
  projects:
    output: true
    permalink: /projects/:name/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
      hero: true

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - README.md
  - vendor

markdown: kramdown
kramdown:
  input: GFM

nav_links:
  - title: Profile
    url: /#profile
  - title: Competencies
    url: /#competencies
  - title: Experience
    url: /#experience
  - title: Projects
    url: /#projects
  - title: Education
    url: /#education
  - title: Contact
    url: /#connect

social:
  email: liam@liamday.co.uk
  linkedin: https://www.linkedin.com/in/liammday/
  github:
  medium:

contact:
  location: Winchester, Hampshire, UK
  phone: 07590 836171
  email: liam@liamday.co.uk
  linkedin: https://www.linkedin.com/in/liammday/
  website: https://www.liamday.co.uk
  security_clearance: DV-cleared (details on request)
  right_to_work: UK citizen
